name: PHP Composer install tests - Ubuntu PPA PHP 8.3

on:
  push:
    branches: [ "FRAMEWORK_6_0" ]
  pull_request:
    branches: [ "FRAMEWORK_6_0" ]
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upgrade to PHP 8.3 from PPA and print PHP version
      run: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt update
        sudo apt install php8.3 php8.3-dom php8.3-pdo php8.3-sqlite3 php8.3-mysql php8.3-curl php8.3-intl php8.3-mbstring php8.3-cli php8.3-fpm
        sudo update-alternatives --set php /usr/bin/php8.3
        which php
        php --version

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies for composer.json as-is
      run: composer install --prefer-dist --no-progress
    - name: Install passwd app
      run: composer require horde/passwd --prefer-dist --no-progress
    - name: Install content tagger app
      run: composer require horde/content --prefer-dist --no-progress
    - name: Install timeobjects app
      run: composer require horde/timeobjects --prefer-dist --no-progress
    - name: Install mnemo notes app
      run: composer require horde/mnemo --prefer-dist --no-progress
    - name: Install ingo mail filter app
      run: composer require horde/ingo --prefer-dist --no-progress
    - name: Install turba addressbook app
      run: composer require horde/turba --prefer-dist --no-progress
    - name: Install kronolith calendar app
      run: composer require horde/kronolith --prefer-dist --no-progress
    - name: Install whups ticketing app
      run: composer require horde/kronolith --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
